### ISSUE TITLE
Wrong Comments Type

### ISSUE THREAD

**Issue by brunowego** [mitzkia/language-syslog-ng#1]
First, thanks for this plugin. Congrats!

The current version are not using the correct comment type using `#`.

**Comment by mitzkia** [comment]
Thank you very much for your comment.
I am trying to upload my new version into atom.io package registry.
I hope it will fix this issue. 

Soon I also wanted to update grammar to identify newer syslog-ng config elements.

**Comment by mitzkia** [comment]
I have pushed my changes. At first only fix comment usage.
Could you please check it? New version is: v0.0.7
Thanks.

**Comment by brunowego** [comment]
@mitzkia works perfectly! Thanks.
